### ISSUE TITLE
Is this Debian only?

### ISSUE THREAD

**Issue by vedrafal** [rkaczorek/virtualgps#3]
Hello,

I am running Ubuntu Mate on my RPI 4 and I am getting an error when I try to run your script. 

After running sudo -u root python3 virtualgps.py I am getting this error:

Traceback (most recent call last):
  File "virtualgps.py", line 62, in <module>
    os.symlink(pty,virtualgps_dev)
FileExistsError: [Errno 17] File exists: '/dev/pts/1' -> '/tmp/vgps'

Is this meant to be run on Debian only?

**Comment by rkaczorek** [comment]
No, it is not debian specific. It means that for some reason the file /tmp/vgps exists while virtual gps is starting. You can safely remove it with `rm -rf /tmp/vgps` and restart virtualgps.

BTW. there is no reason to run virtualgps as root

**Comment by vedrafal** [comment]
Thank you very much, that did it. I'm running it as service now and everything is working.
