### ISSUE TITLE
Bug at line 56

### ISSUE THREAD

**Issue by msaber** [rkaczorek/virtualgps#6]
Line 56 is a not correct! 
len(elements) can be 1, and there would not be any elements[1]

**Comment by rkaczorek** [comment]
Are you sure? The code reads:
```
if len(elements) > 0:
    # Convert minutes to degrees
    degrees += float(elements[1]) / 60
if len(elements) > 1:
    # Convert seconds to degrees
    degrees += float(elements[2]) / 3600
return degrees
```

and this means that the first if statement does pick elements[1], doesn't it?
