### ISSUE TITLE
location.conf coordinates format

### ISSUE THREAD

**Issue by kalgecin** [rkaczorek/virtualgps#7]
The provided location.conf contains coordinates in decimal format, while the services expects it in deg:min:sec format. Took me a while to see why my virtualgps was failing to start

**Comment by rkaczorek** [comment]
I don't think so. Both formats are supported. See examples below, respectively decimal and sexagesimal: 

```
$ cat /etc/location.conf 
[default]
latitude  = 52.13791
longitude = 21.00704
elevation = 100.0

$ python3 virtualgps.py 
52.13791
21.00704
100.0

$ cat /etc/location.conf 
[default]
latitude = 52:25:34.89
longitude = 20:50:55.44
elevation = 100.0

$ python3 virtualgps.py 
52.42635833333333
20.848733333333332
100.0
```

**Comment by kalgecin** [comment]
must be my astroberry installation then..... it was crashing the virtualgps service with the decimal format until i changed it. errors about parsing
```
astroberry@astroberry:~ $ /usr/bin/python3 /usr/bin/virtualgps.py
Traceback (most recent call last):
  File "/usr/bin/virtualgps.py", line 100, in <module>
    latitude = convert_to_sexagesimal(config['default']['latitude'])
  File "/usr/bin/virtualgps.py", line 56, in convert_to_sexagesimal
    degrees += float(elements[1]) / 60
IndexError: list index out of range
```

**Comment by rkaczorek** [comment]
This error is already fixed. Update your system or if you don't want to, manually replace /usr/bin/virtualgps.py with the file from repository

**Comment by kalgecin** [comment]
cool thanks
