### ISSUE TITLE
Not Working on Arch

### ISSUE THREAD

**Issue by Helmet93** [rkaczorek/virtualgps#9]
Hello,

I was hoping to use this on my desktop running Arch without a GPS of any sort in it. I installed, enabled, and started `gpsd`, I have also followed the instructions on your Readme.md to use it as a system wide service. It is not working and I am still only getting location from my ISP (Not correct).

When I check the service status, I get this:
```
● virtualgps.service - Virtual GPS
     Loaded: loaded (/etc/systemd/system/virtualgps.service; enabled; preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2023-04-16 16:19:22 EDT; 2s ago
    Process: 4711 ExecStart=/usr/bin/python3 /usr/bin/virtualgps.py (code=exited, status=217/USER)
    Process: 4712 ExecStartPost=sleep 3 (code=exited, status=217/USER)
    Process: 4714 ExecStopPost=/usr/sbin/gpsdctl remove /tmp/vgps (code=exited, status=217/USER)
   Main PID: 4711 (code=exited, status=217/USER)
        CPU: 2ms
```

**Comment by rkaczorek** [comment]
Is python executable available in `/usr/bin/python3`?
